export const GET_POKEMONS = 'pokemon/get'
export const NAME_POKEMON = 'pokemon/name'
export const GET_TYPE = 'type/get'
export const FILTER_TYPE =  'type/filter'
export const ORDER_BY = 'order/by'
export const ORDER_BY_POWER = 'power/by/order'
export const FILTER_CREATE = 'create/filter'
export const CREATE_POKEMON = 'post/pokemon'